### ISSUE TITLE
Pinax-teams is not running.

### ISSUE THREAD

**Issue by Tikam02** [pinax/pinax-teams#62]
(site) root@hal:~/Desktop/pin/mysite# ./manage.py runserver
Unhandled exception in thread started by <function check_errors.<locals>.wrapper at 0x7fa60de34488>
Traceback (most recent call last):
  File "/root/Desktop/pin/site/lib/python3.6/site-packages/django/utils/autoreload.py", line 225, in wrapper
    fn(*args, **kwargs)
  File "/root/Desktop/pin/site/lib/python3.6/site-packages/django/core/management/commands/runserver.py", line 113, in inner_run
    autoreload.raise_last_exception()
  File "/root/Desktop/pin/site/lib/python3.6/site-packages/django/utils/autoreload.py", line 248, in raise_last_exception
    raise _exception[1]
  File "/root/Desktop/pin/site/lib/python3.6/site-packages/django/core/management/__init__.py", line 327, in execute
    autoreload.check_errors(django.setup)()
  File "/root/Desktop/pin/site/lib/python3.6/site-packages/django/utils/autoreload.py", line 225, in wrapper
    fn(*args, **kwargs)
  File "/root/Desktop/pin/site/lib/python3.6/site-packages/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/root/Desktop/pin/site/lib/python3.6/site-packages/django/apps/registry.py", line 93, in populate
    "duplicates: %s" % app_config.label)
django.core.exceptions.ImproperlyConfigured: Application labels aren't unique, duplicates: account

**Comment by KatherineMichel** [comment]
What are the app labels that are the same. Do you know? Apparently this is a problem that began with Django 1.7.

**Comment by KatherineMichel** [comment]
Closing for now, if you need more assistance, feel free to join our Slack.
